version: '3.1'

services:
  app:
    build: .
    command: yarn prisma migrate dev
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:latest
    container_name: keep_focus_mysql_
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: _keep_focus_
      MYSQL_USER: iury
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./volumes/mysql_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
